### PR TITLE
Add aspect ratio to Kit_OutputFormat

### PR DESCRIPTION
**Pull request by jsm174**
We have an app that needs to know the video's aspect ratio. 

This PR adds the aspect ratio information from the `codec_ctx->sample_aspect_ratio` to the `Kit_OutputFormat` structure.

Maybe others would find it useful too.

### CODE REVIEW

**Comment by katajakasa** [comment]
Thanks for the PR! Since this changes the API, I will queue it up for the next major version bump (probably sometime this autumn).

**Comment by katajakasa** [comment]
Right, I had some time to look into this (finally!). I'm thinking that this is probably not the best way to do this. Instead, it would be better to make a new function to return these values, so that no API breakage is required. For example, ```int Kit_GetPlayerAspectRatio(const Kit_Player *player, int *num, int *den); ```, where return value is 0 if values were set, or 1 if there is no video stream.

This does make the API a bit inconsistent since some data is in the struct and some must be acquired via functions, but I think the raw structs were probably a bad idea to begin with. Function getters are probably the way of the future for this library :/

**Comment by katajakasa** [comment]
Fyi: alternative implementation coming up here https://github.com/katajakasa/SDL_kitchensink/pull/75 -- turns out that getting the aspect ratio out in all cases is a bit more involved than expected :P

**Comment by jsm174** [comment]
awesome. Thank you very much for this!

**Comment by katajakasa** [comment]
Thanks for the suggestion! New release rolled https://github.com/katajakasa/SDL_kitchensink/releases/tag/1.0.12

Closing this as done :)

**Pull request closed without merging**
